"""creates comment table

Revision ID: 5abec66e11f9
Revises: ec3a874c2f39
Create Date: 2021-04-14 18:26:24.105731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5abec66e11f9"
down_revision = "ec3a874c2f39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("close_votes", sa.Integer(), nullable=True),
        sa.Column("closed_by_user_id", sa.String(), nullable=True),
        sa.Column("last_editor_user_id", sa.String(), nullable=True),
        sa.Column("owner_user_id", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_editor_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###
