"""creates a qanet_user table.

Revision ID: 6f2a8b3c68fa
Revises:
Create Date: 2021-04-14 07:04:01.038285

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger


# revision identifiers, used by Alembic.
revision = "6f2a8b3c68fa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qanet_user",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.Binary(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "ix_qanet_user_search_vector",
        "qanet_user",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # trigger to sync the full text columns
    conn = op.get_bind()
    sync_trigger(conn, "qanet_user", "search_vector", ["id", "email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_qanet_user_search_vector", table_name="qanet_user")
    op.drop_table("qanet_user")
    # ### end Alembic commands ###
