"""creates post table


Revision ID: ec3a874c2f39
Revises: cf82fa87a444
Create Date: 2021-04-14 14:30:27.303437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec3a874c2f39"
down_revision = "cf82fa87a444"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_type", sa.Integer(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("answers_count", sa.Integer(), nullable=True),
        sa.Column("accepted_answer_id", sa.Integer(), nullable=True),
        sa.Column("bookmarks_count", sa.Integer(), nullable=True),
        sa.Column("close_vote", sa.Integer(), nullable=True),
        sa.Column("closed_by_user_id", sa.String(), nullable=True),
        sa.Column("closed_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("last_editor_user_id", sa.String(), nullable=True),
        sa.Column("owner_user_id", sa.String(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_answer_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_editor_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["qanet_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assoc_question_post_tags",
        sa.Column("post_tag_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_tag_id"],
            ["post_tag.id"],
        ),
        sa.PrimaryKeyConstraint("post_tag_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assoc_question_post_tags")
    op.drop_table("post")
    # ### end Alembic commands ###
