# @name addAnswer - shan
POST {{host}}/questions/1/answers HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"answer": "shan answer OWN (1)."
}
###

# @name addAnswer - raj
POST {{host}}/questions/1/answers HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{rajToken}}

{
	"answer": "raj answer (2)."
}
###

# @name addAnswer - sherlock
POST {{host}}/questions/1/answers HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{sherlockToken}}

{
	"answer": "sherlock answer (3)."
}
###

# @name updateAnswer
PUT  {{host}}/questions/1/answers/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"answer": "my first answer updated again."
}
###


# @name deleteAnswer
DELETE {{host}}/questions/1/answers/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name acceptAnswer - raj
POST {{host}}/questions/1/answers/1/accept HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name fetchAnswers
GET {{host}}/questions/1002/answers?index=0 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# =================== COMMENTS ==========================
# @name addComments - shan
POST {{host}}/answers/1/comments HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	comment: "I will change from this to another very quickly. (8)"
}
###

# @name fetchComments - question 1
GET {{host}}/answers/1/comments?index=0 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name editComment - edit shan comment using sherlock token.
PUT {{host}}/answers/1/comments/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	comment: "I like raymond redington and will come over the current struggles"
}
###

# @name deleteComment
DELETE {{host}}/answers/1/comments/1 HTTP/1.1
Authorization: {{shanToken}}
###

# =================== VOTE ==========================
# 1 - upvote, 2 - downvote, 3 - zero (undo)
POST {{host}}/answers/2/vote/0 HTTP/1.1
Authorization: {{sherlockToken}}