# @name signin
POST {{host}}/account/signin HTTP/1.1
Content-Type: {{contentType}}

{
	"userid": "shan",
	"password": "mozzie"
}
###

# @name signin
POST {{host}}/account/signin HTTP/1.1
Content-Type: {{contentType}}

{
	"userid": "raj",
	"password": "mozzie"
}
###

# @name signin
POST {{host}}/account/signin HTTP/1.1
Content-Type: {{contentType}}

{
	"userid": "sherlock",
	"password": "mozzie"
}
###
