
# @name createQuestion
POST {{host}}/questions HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"title": "Is go oo language?",
	"shortDescription": "GO",
	"tags": ["go"],
	"question": "Is go oo language?"
}
###

# @name Fetch question
GET {{host}}/questions/1004 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name updateQuestion
PUT {{host}}/questions/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"title": "EF Core updated",
	"shortDescription": "EF",
	"tags": ["csharp", "fsharp"],
	"question": "how to create cascade delete in fluent api voww shan"
}
###

# @name deleteQuestion
DELETE {{host}}/questions/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name fetchQuestions
GET {{host}}/questions?index=0 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# =================== COMMENTS ==========================
# @name addComments - shan
POST {{host}}/questions/2002/comments HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	comment: "I will change from this to another very quickly. (8)"
}
###

# @name fetchComments - question 1
GET {{host}}/questions/2002/comments?index=1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}
###

# @name editComment - edit shan comment using sherlock token.
PUT {{host}}/questions/1/comments/7 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	comment: "I like raymond redington and will come over the current struggles"
}
###

# @name deleteComment
DELETE {{host}}/questions/1/comments/8 HTTP/1.1
Authorization: {{shanToken}}
###

# =================== VOTE ==========================
# 1 - upvote, 2 - downvote, 3 - zero (undo)
POST {{host}}/questions/1/vote/1 HTTP/1.1
Authorization: {{sherlockToken}}
