
# @name createTag
POST {{host}}/tags HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"id": "csharp",
	"description": "oo language"
}
###

POST {{host}}/tags HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{shanToken}}

{
	"id": "fsharp",
	"description": "functional language"
}
###

# @name fetchtags
GET {{host}}/tags HTTP/1.1

###